name: Build Plugin

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Echo exact java version being used
        run: java -version
      - name: Get Tag Name
        id: tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Execute Gradle Build
        run: ./gradlew build -Pbuild.release=true

      - name: Publish Jars
        run: ./gradlew publish
        env:
          PUBLISH_TOKEN: ${{secrets.MAVEN_PUBLISH_TOKEN}}
          VERSION: ${{steps.tag_name.outputs.VERSION}}